### ISSUE TITLE
Adding long[] member to PhotoMetadata

### ISSUE THREAD

**Issue by MaximLippeveld** [jgperrin/net.jgp.books.sparkWithJava.ch09#5]
Hi,

Thanks for the great tutorial!

Question: is it possible to add an array of `long`'s as a member to the PhotoMetadata class? I have tried it, but I get the following exception:
```
Caused by: java.lang.ClassCastException: [J cannot be cast to [B
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getBinary(rows.scala:47)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getBinary(rows.scala:195)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(generated.java:48)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:253)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any help is appreciated!

Kind regards,
Maxim

**Comment by jgperrin** [comment]
Thanks, @MaximLippeveld - do not hesitate to give 5 stars at https://amzn.to/3gyFDHk ;)...

I am not sure what you are trying to do here. Why would you want an array of longs? To group all long-based properties?

(sorry for the delay in answering, my GitHub emails were going to limbo!)

**Comment by MaximLippeveld** [comment]
Hi, thanks for you reply. Not sure any more what I was trying to do back then :grin:

**Comment by jgperrin** [comment]
lol - that's the best tech support I gave in years :). Thanks for reading the book. I'll close the ticket now.
